services:
- type: web
  name: hip-money-management
  env: node
  plan: free
  buildCommand: npm install
  startCommand: npm start
  envVars:
  - key: NODE_ENV
    value: production
  - key: DATABASE_FILE
    value: /data/data.sqlite
  disk:
    name: data
    mountPath: /data
    sizeGB: 1

